server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/c85-s3-ppk-blog?serverTimezone=UTC&CharsetEncoding=utf-8&useSSL=false
    username: root
    password: a
    driver-class-name: com.mysql.jdbc.Driver
    
    
logging:
  level:
    com:
      yc:
        C86S3Ppkblog: debug
