server:
  port: 80

# 定义当前服务名
spring:
   application:
      name: serverzuul
# 配置Eureka 服务器的地址
eureka:
   client:
      serviceUrl:
         defaultZone: http://es2:7999/eureka,http://es1:8000/eureka
         
# zuul 路由配置
# http://es3/user/user   ==>   http://es1:8001/user
# http://es3/order/order ==>   http://es1:8002/order

zuul:
  # 后面不定义配置参数, 表示 无敏感头 ==> 空集合
  # 全局敏感头设置
  sensitiveHeaders: Cookie,Set-Cookie,Authorization
  routes:
     # 忽略路由
    #ignoredServices: '*'
    #ignoredPatterns: /simple/**
     # 路由名 (简单路由)
    simple:
      #映射地址
      path: /simple/163
      #简单路由url地址使用http和https开头的地址
      url: http://www.163.com
      
    #路由名(跳转路由) 跳转到当前项目的某个action方法
    forward: 
      #映射地址
      path: /forward/**
      #使用forward:开头
      url: forward:/test
    


    # 路由名(Ribbn路由)
    user:
      # 对应接口的地址  /** 表示所有的接口(包含子目录)
      path: /u/**
      #配置服务名
      serviceId: serverUser
       # 敏感头设置,  数据类型是集合
      # sensitiveHeaders: Authorization
     

    # 路由名
   # order:
      # 对应接口的地址  /** 表示所有的接口(包含子目录)
    #  path: /o/**
      #路由名和服务名一致，可以省略服务名配置
     # serviceId: serverOrder
      
      #  默认路由
    # http://127.0.0.1/  ==> http://www.hyycinfo.com
    # http://127.0.0.1/test/test  ==> http://www.hyycinfo.com/test/test 404
    legacy:
      path: /**
      url: http://www.hyycinfo.com
      
      
hystrix:
   command:
      default:
         execution:
            isolation:
               thread:
                  timeoutInMilliseconds: 60000
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000
    