server:
   port: 8000

spring:
   application:
      name: server

eureka:
   client:
      registerWithEureka: false
      fetchRegistry: false
      serviceUrl:
         defaultZone: http://127.0.0.1:8000/eureka

